### ISSUE TITLE
Mechjeb2 class changed

### ISSUE THREAD

**Issue by SupernovaXTS** [Genhis/KRPC.MechJeb#16]
**Describe the bug**

Using 2.12.x and KRPC does not see mechjeb
**Expected behavior**

Working
**Code snippet to reproduce it (ideally in Python)**
```
<!-- Paste your code snippet here -->
```

**Screenshots**

**Version details**
kRPC.MechJeb: 0.61

Kerbal Space Program: 1.11.1
kRPC: 0.48
MechJeb2: 2.12.x

**Comment by Genhis** [comment]
Can you attach KSP.log, please? Does any popup from kRPC.MechJeb show up during the loading screen?

**Comment by SupernovaXTS** [comment]
closing the issue it actually works,
