### ISSUE TITLE
AirplaneAutopilot class issue

### ISSUE THREAD

**Issue by jxpsert** [Genhis/KRPC.MechJeb#17]
**Describe the bug**
kRPC seems to not work (using [Kerbal Telemetry](https://github.com/yagiziskirik/Kerbal-Telemetry))
When starting a launch, the message supplied in the screenshots area appears. 

**Expected behavior**
Not receiving an error and kRPC functioning with Kerbal Telemetry

**Code snippet to reproduce it (ideally in Python)**
Not applicable

**Screenshots**

![image](https://user-images.githubusercontent.com/65042215/109215716-d87f3a00-77b3-11eb-98c0-1dac8a32dd26.png)

**Version details**
kRPC.MechJeb: 0.6.1

Kerbal Space Program: 1.10.1
kRPC: 0.4.8
MechJeb2: 2.11.0

**Comment by Genhis** [comment]
Indeed, this is a known issue. MechJeb changed their internals of `AirplaneAutopilot` a few versions back and I haven't had time to fix it. Last known working version is 2.9.2.0.

I would gladly accept any help with this issue if you want to try. If not, I think I could find time to fix it in a month or so.

Out of interest, what is your use case for AirplaneAutopilot?

**Comment by jxpsert** [comment]
I'm not really into KSP coding myself, sorry.

I'm not deliberately using it AirplaneAutopilot. I'm using a telemetry mod that uses kRPC and kRPC.MechJeb, and I think that's using it. It has a stage button and will have more MechJeb controls - the stage button is the thing not working.

I'll keep following for a possible fix for this issue :)

**Comment by Genhis** [comment]
So, are you flying airplanes or just rockets? Can you attach your KSP.log, please?

**Comment by jxpsert** [comment]
Just rockets, for now.
And here's the log file as well. I only shut down now, so there's probably a lot to scroll through.
I've taken a look at it myself and I think it's to do with line 82106 and the 'not found' lines under it.
[KSP.log](https://github.com/Genhis/KRPC.MechJeb/files/6045799/KSP.log)

**Comment by Genhis** [comment]
It's hard to tell but the issue seems to be related to MechJeb:

    [ERR 21:16:10.003] MechJeb module MechJebModuleSpaceplaneAutopilot threw an exception in OnStart: System.NullReferenceException: Object reference not set to an instance of an object

I have not implemented MechJebModuleSpaceplaneAutopilot yet and I am not aware of calling it anywhere. But just to be sure, can you test it with MechJeb 2.9.2.0 and report back if the issue still occurs (and share your log file again)?

**Comment by jxpsert** [comment]
I'll try that tomorrow, going to bed in a few minutes.
Thanks for helping me at least, and I'll get back to you :)

**Comment by jxpsert** [comment]
Sadly, 2.9.2.0 doesn't seem to be compatible with KSP 1.10.1

I might just go on with the newest version and return using this when it becomes compatible. Thank you for your help, though!

**Comment by Genhis** [comment]
It's true that the version is not officially compatible but it should work fine if you want to try.

**Comment by jxpsert** [comment]
I tried anyways, and it worked!
I'll still keep on the lookout for an update if one may arrive :)

Thank you.

**Comment by Genhis** [comment]
This should be fixed by #19.
