### ISSUE TITLE
autostage_limit attribute in staging controller is not read/writable

### ISSUE THREAD

**Issue by Ernesto-Alvarez** [Genhis/KRPC.MechJeb#2]
While configuring the autopilot, I noticed that, contrary to the documentation, the StagingController.autostage_limit does not change MJ2's configuration.

To reproduce:
Put a vehicle on the launch pad.
Fill the options->stop at stage# field with something characteristic (6 in the example)
Run the following program:

>>> import krpc
>>> 
>>> conn = krpc.connect(name="Launch into orbit")
>>> 
>>> sc = conn.space_center
>>> mj = conn.mech_jeb
>>> ascent = mj.ascent_autopilot
>>> st = ascent.staging_controller
>>> st.autostage_limit
6
>>> st.autostage_limit = 1
>>> st.autostage_limit
6

The program reports the correct value for the field but ignores the assignment. The field does not change in MJ2's window in KSP. The attribute remains unchanged after assignment, but changes if new value is punched in via MJ2 window.

**Comment by Genhis** [comment]
Hi,
I will look into it this weekend and release a fix by Sunday

**Comment by Ernesto-Alvarez** [comment]
Thanks!
I really like your plugin. It's great for rocket testing.
Great work!
