### ISSUE TITLE
Update Python class docs to use snake_case instead of PascalCase

### ISSUE THREAD

**Issue by ChucklesTheBeard** [Genhis/KRPC.MechJeb#23]
ex: the class https://genhis.github.io/KRPC.MechJeb/python/landing-autopilot.html shows `LandingAutopilot`, the actual client uses `landing_autopilot`

**Comment by Genhis** [comment]
Thanks for the report; however, this is correct. `LandingAutopilot` is a class name and `conn.mech_jeb.landing_autopilot` is an instance of this class. This is also the case in kRPC documentation where classes (such as [CelesialBody](https://krpc.github.io/krpc/python/api/space-center/celestial-body.html)) use PascalCase but variable names are snake_case.

This page shows all properties (snake_case) which you can access via `conn.mech_jeb` instance: https://genhis.github.io/KRPC.MechJeb/python/mechjeb.html#MechJeb.landing_autopilot

**Comment by ChucklesTheBeard** [comment]
Makes sense! Thank you, and my apologies for wasting your time. :)
