### ISSUE TITLE
Add a service json file

### ISSUE THREAD

**Issue by Overloader6** [Genhis/KRPC.MechJeb#25]
**Which MechJeb2 module is your feature request related to?**
None, its a general feature for the mod

**Is your feature request related to a problem? Please describe:**
This project seems to support Python, Lua, etc as well as C-nano, C++, C# and Java clients. However if you use another library, for example https://github.com/Cahu/krpc-mars for rust, this module wont be usable.

**Describe the solution you would like:**
All the rust library needs is a service json file like the bas KRPC mod already offers, probably named `KRPC.MechJeb.json`. From there the rust library and probably others can generate bindings.

**Comment by Genhis** [comment]
Okay, it will be part of future builds. For [v0.7.0](https://github.com/Genhis/KRPC.MechJeb/releases/tag/v0.7.0), I added the file separately.
