### ISSUE TITLE
KRPC fails to load with KRPC.MechJeb

### ISSUE THREAD

**Issue by ghost** [Genhis/KRPC.MechJeb#26]
**Describe the bug**
KRPC does not show up in game if KRPC.MechJeb is installed. MechJeb and KRPC work fine without this.

**Expected behavior**
Expecting it to add functionality to KRPC. 

**Version details**
kRPC.MechJeb: 0.7.0

Kerbal Space Program: 1.12.5
kRPC: 0.5.4
MechJeb2: 2.14.3.0

**Comment by 0x00ASTRA** [comment]
I have updated the krpc target and rebuilt the project. Tested and working on my machine.

[KRPC.MechJeb-Continued - Bugfix Release ](https://github.com/0x00ASTRA/KRPC.MechJeb-Continued/releases/tag/bugfix)

**Comment by Genhis** [comment]
> I have updated the krpc target and rebuilt the project. Tested and working on my machine.

Thank you for fixing this issue. I'll make a release in a few weeks because I am busy with other things at the moment.

**Comment by 0x00ASTRA** [comment]
No worries. Thank you for creating such a useful piece of software! I made a [release](https://github.com/0x00ASTRA/KRPC.MechJeb-Continued/releases/tag/bugfix) available in the mean time, just to get it working for folks if they so desire. All I did was update the csproj file with version 5.2 for KRPC and rebuilt the dll. Quick fix 😄
