### ISSUE TITLE
Enforce coding convetions through .editorconfig file for Visual Studio

### ISSUE THREAD

**Issue by vkribo** [Genhis/KRPC.MechJeb#6]
You could enforce tab indentation, curly brace on same line, this. preferences and other things.
https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2019

**Comment by Genhis** [comment]
It's done in master branch :) https://github.com/Genhis/KRPC.MechJeb/blob/master/.editorconfig

I will merge `dev` to `master` this week and release the version 0.5.0. After that, it should be enforced/suggested for all contributors.

**Comment by vkribo** [comment]
Nice, I didn't notice :)
